[GPIO]
chip_name=/dev/gpiochip0
trg_lines=[73, 228, 229]

#[HC-SR04]
[length]
line=69 # GPIO, Phys=13
base=83 # cm
name=length

[width]
line=75 # GPIO, Phys=12
base=46
name=width

[height]
line=79 # GPIO, Phys=16
base=33
name=height

[hx711]
data_pin=231
clock_pin=232
ref_unit=100
offset=-24753

[PG]
pg_host=vm-pg-devel.arc.world
pg_user=arc_energo
